language: java
jdk:
  - openjdk8
cache:
  directories:
    - '$HOME/.docker'
    - '$HOME/.gradle'
services:
  - docker
before_script:
  - docker-compose up -d
  - make database
script:
  - ./gradlew clean build           # 빌드
  - ./gradlew detekt                # 정적 분석
  - ./gradlew test jacocoTestReport # 테스트 코드 실행 및 coverage
